# Generated by Django 4.2.1 on 2023-06-16 01:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_quantity', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('milk_quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('liter_price', models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('breeders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pages.breeders')),
            ],
        ),
        migrations.CreateModel(
            name='Breeder_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_quantity', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('breeders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.breeders')),
            ],
        ),
    ]
