# Generated by Django 4.2.1 on 2023-06-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
    ]
