# Generated by Django 4.2.1 on 2023-06-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_profile_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
