# Generated by Django 4.2.1 on 2023-06-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
