# Generated by Django 4.2.1 on 2023-06-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_creation',
        ),
    ]
