# Generated by Django 4.2.1 on 2023-06-19 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_orders_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_confirm',
            name='item',
        ),
        migrations.AddField(
            model_name='orders_confirm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
