# Generated by Django 4.2.1 on 2023-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_orders_confirm_item_orders_confirm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
